#!/bin/bash
# Copyright (c) 2014 The CoreOS Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e
umask 0022

INSTALL_MNT=$(dirname "$0")
INSTALL_DEV="$1"

# use the fw_setenv binary from the image to ensure compatibility
FW_SETENV=
for bindir in bin/old_bins bin sbin usr/bin; do
    if [[ -x "${INSTALL_MNT}/${bindir}/fw_setenv" ]]; then
        FW_SETENV="${INSTALL_MNT}/${bindir}/fw_setenv"
        break
    fi
done
if [[ -z "${FW_SETENV}" ]]; then
    echo "Failed to locate the fw_setenv binary in ${INSTALL_MNT}" >&2
    exit 1
fi

FW_PRINTENV=
for bindir in bin/old_bins bin sbin usr/bin; do
    if [[ -x "${INSTALL_MNT}/${bindir}/fw_printenv" ]]; then
        FW_PRINTENV="${INSTALL_MNT}/${bindir}/fw_printenv"
        break
    fi
done
if [[ -z "${FW_PRINTENV}" ]]; then
    echo "Failed to locate the fw_printenv binary in ${INSTALL_MNT}" >&2
    exit 1
fi

WACOM_FLASH=
for bindir in bin/old_bins bin sbin usr/bin; do
    if [[ -x "${INSTALL_MNT}/${bindir}/wacom_flash" ]]; then
        WACOM_FLASH="${INSTALL_MNT}/${bindir}/wacom_flash"
        break
    fi
done
if [[ -z "${WACOM_FLASH}" ]]; then
    echo "Failed to locate the wacom_flash binary in ${INSTALL_MNT}" >&2

fi

# locate the dynamic linker
LDSO=
for l in "${INSTALL_MNT}"/lib*/ld-2.??.so; do
    if [[ -x "$l" ]]; then
        LDSO="$l"
        break
    fi
done
if [[ -z "${LDSO}" ]]; then
    echo "Failed to locate ld.so in ${INSTALL_MNT}" >&2
    exit 1
fi
LIBS="${LDSO%/*}"

call_fw_setenv() {
    "${LDSO}" --library-path "${LIBS}" "${FW_SETENV}" -c "${INSTALL_MNT}/etc/fw_env.config" "$@"
}
call_fw_printenv() {
    "${LDSO}" --library-path "${LIBS}" "${FW_PRINTENV}" -c "${INSTALL_MNT}/etc/fw_env.config" "$@"
}
call_wacom_flash() {
    "${LDSO}" --library-path "${LIBS}" "${WACOM_FLASH}" "$@"
}


call_fw_setenv "upgrade_available" "1"

OLDPART=$(call_fw_printenv -n active_partition)
NEWPART="${INSTALL_DEV: -1}"
if [[ "${OLDROOT}" == "${INSTALL_DEV}" ]]; then
    echo "WARNING: We're installing over our current root"
else
    call_fw_setenv "fallback_partition" "${OLDPART}"
    call_fw_setenv "active_partition" "${NEWPART}"
fi

cat "${INSTALL_MNT}/usr/share/remarkable/update.conf"
echo "Setup ${INSTALL_LABEL} (${INSTALL_DEV}) for next boot."

if [[ -n "${WACOM_FLASH}" ]] && [[ -r "${INSTALL_MNT}/lib/firmware/W9013_0734.hex" ]]; then
    call_wacom_flash "${INSTALL_MNT}/lib/firmware/W9013_0734.hex" "0" "i2c-1"
fi
