#!/bin/bash
# Copyright (c) 2014 The CoreOS Authors.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

bootdev=$(fw_printenv -n mmcroot)

if [[ "$bootdev" == "$(rootdev)" ]]; then
    fw_setenv upgrade_available 0
    fw_setenv bootcount 0
fi
